### ISSUE TITLE
Scheduler custom view demo throws an exception while destroying recursive event

### ISSUE THREAD

**Issue by rockstartstudent** [telerik/ui-for-aspnet-mvc-examples#13]
I ran this project and its working perfectly fine for add/edit event but not for destroy(delete). When we destroy any recursive event it throws below exception on line db.SaveChanges(); in "Delete(MeetingViewModel meeting, ModelStateDictionary modelState)" method.

Exception - Store update, insert, or delete statement affected an unexpected number of rows (0). Entities may have been modified or deleted since entities were loaded. Refresh ObjectStateManager entries.

![concurrency exception](https://cloud.githubusercontent.com/assets/26761473/24443960/594f1a2c-1482-11e7-99d3-763a21e26a47.png)

**Comment by mparvanov** [comment]
The issue was not reproduced.
A possible cause for the error could be that a SQL server process is locking the Sample.mdf file under SchedulerCustomViewDemo\App_Data
