### ISSUE TITLE
Scripts folder missing for ui-for-aspnet-mvc-examples/grid/grid-dpl-integration/GridExcelSpreadProcessing/

### ISSUE THREAD

**Issue by shawncodewell** [telerik/ui-for-aspnet-mvc-examples#14]
I've cloned the repo, and found the scripts folder to be missing for the ui-for-aspnet-mvc-examples/grid/grid-dpl-integration/GridExcelSpreadProcessing/ sample.  Please help.

**Comment by shawncodewell** [comment]
Specifically, the _Layout.cshtml page references script <script src="@Url.Content("~/Scripts/kendo.modernizr.custom.js")"></script> but it ain't there.

**Comment by VicTachev** [comment]
The script is not essential for the example and you can safely ignore the error. Furthermore, you can remove the reference from the _Layout file and there will not be an error in the console when running the sample.
