### ISSUE TITLE
'DataSourceRequestModelBinder' sample is not compatible with ASP.NET Core 2.0.0

### ISSUE THREAD

**Issue by Eilon** [telerik/ui-for-aspnet-mvc-examples#15]
Moving from https://github.com/aspnet/Mvc/issues/6600

This line of code here: https://github.com/telerik/ui-for-aspnet-mvc-examples/blob/master/scheduler/scheduler-web-api-crud/SchedulerWebApiCrud/ModelBinders/DataSourceRequestModelBinder.cs#L68

Is calling an API that was [marked as obsolete](https://github.com/aspnet/Mvc/blob/49a48a0a3352135b38a373c7d7a9cbbdc9ee97bf/src/Microsoft.AspNetCore.Mvc.Core/ModelBinding/ValueProviderResultExtensions.cs#L12-L13) in ASP.NET Core 1.1, and was then [removed in ASP.NET Core 2.0](https://github.com/aspnet/Mvc/issues/5063).

You can see the commit where the API was removed to see the alternative pattern that will still work: https://github.com/aspnet/Mvc/commit/824d65ca3d6da81864c24350d6fb0d612a9c1d31#diff-161a3b0396461c85730bbbe25b9d5ac7L383

**Comment by grahamehorner** [comment]
Also after review the telerik code for the Telerik UI for ASPNET Core it make use of classes that are within the Microsoft.AspNetCore.Mvc.Internal namespace; namely the TaskCache, please update and make ASPNET Core 2.0 compatible.

**Comment by cpalomares** [comment]
Has this been fixed yet ? I have same problem using.net core 2.0

**Comment by OptivolveRodanAlSaleh** [comment]
I have same proplem using .net core 2, any update?

**Comment by grahamehorner** [comment]
I have raised the issue with telerik and they are working on update to address the breaking changes of asp.net core 2.0 and have given a eta of Sept. for a release.  It should be noted that telerik have been using classes within Microsoft internal make space IMHO this bad practice and is why the telerik code broke with asp.net core 2 releases

**Comment by grahamehorner** [comment]
@1amirjalai nope, unless you wish to fork the code for telerik or asp,net core 2.0 MVC and re-implement the internal methods which Telerik used. (IMHO isn't the correct thing to do)  I'm afraid its a wait for a new release from Telerik. :'(

**Comment by 1amirjalai** [comment]
@grahamehorner when will be release date?
Telerik has announced at their [website ](http://www.telerik.com/forums/net-core-2-0-support#PoFE_1eY40G2wddlNVcnSQ) it would be mid September but it's too late around three weeks from now.
There are many bugs in asp.net core 1.1.2 that are corrected is 2.0

**Comment by grahamehorner** [comment]
@1amirjalai I can't speak for Telerik as I'm only a user of the product; but I can say Telerik support told me they are working on an update; and the ETA is as published mid September.  If this is to late for you; I would suggest reaching out to Telerik support to request a hotfix and/or an internal release or see what they could do to assist.

**Comment by VicTachev** [comment]
The [fix for this issue ](https://github.com/telerik/kendo-ui-core/issues/3546)was included in the R3 2017 release. Thus, the error should not be observed with the current version of the components. 

Please upgrade to the latest release and see how it works for you. The current version is R3 2017 SP2 (2017.3.1026).
