### ISSUE TITLE
SalesHub.mdf is missing from the repository

### ISSUE THREAD

**Issue by AZDeveloper777** [telerik/ui-for-aspnet-mvc-examples#16]
Subject says it all.
Please make this file available for download or include it in the repository.

**Comment by VicTachev** [comment]
SalesHub database is generated on the fly when running the project. 

I tested the example and it is working as expected on my end. The only modification I made was changing the ConnectionString. 

Check [this video for reference](https://www.screencast.com/t/fLed28CLub0o).
