### ISSUE TITLE
ASPNETCORE SignalR

### ISSUE THREAD

**Issue by grahamehorner** [telerik/ui-for-aspnet-mvc-examples#17]
Please look at the new SignalR development (preview) and consider creating a open source component library and new guidance on creating real-time server side databinding with telerik components.

**Comment by VicTachev** [comment]
Hello @grahamehorner ,

Currently SignalR for ASP.NET Core 2.0 is not supported in the components. Such implementation is not in our immediate plans and I cannot give an exact time frame as to when it will be included in the planning.
