### ISSUE TITLE
May i download the saleshub code independently from the rest ?

### ISSUE THREAD

**Issue by abel406** [telerik/ui-for-aspnet-mvc-examples#18]
Hi. I have a very slow internet connection. Would you be so kind of create a separate download so i could get just that ?

The complete examples code is about 900 and change MB. To big for my bandwidth. Thanks in advance.

**Comment by VicTachev** [comment]
Hello,

By default GitHub gives the option to download the whole repository. However, you can try external tools that provide such capability. 

I tried [GitZip](http://kinolien.github.io/gitzip/) and it works as expected on my end. Note that you would need to generate a [personal access token](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/).
