### ISSUE TITLE
Grid Editing with Nullable boolean

### ISSUE THREAD

**Issue by shawndewet** [telerik/ui-for-aspnet-mvc-examples#19]
When I try to apply this approach:
https://github.com/telerik/ui-for-aspnet-mvc-examples/tree/master/grid/grid-inline-editing-with-nullable-boolean

I get this error:
 The nullableBoolean binding is not supported by the DropDownList widget

**Comment by VicTachev** [comment]
I tried the example with the older and the latest version and editing works as expected on my end. 

Would you submit a ticket with a sample project where the error you are seeing is replicated? This will enable us to examine the behavior and look for what is causing the error.
