### ISSUE TITLE
.Net Core 2.1 Update for grid-handling-unauthorized-request

### ISSUE THREAD

**Issue by dresdor** [telerik/ui-for-aspnet-mvc-examples#20]
Is there any way the example for grid-handling-unauthorized-request can be updated to .net core 2.1?  There have been deprecations and the code does not easily translate into .net core

**Comment by VicTachev** [comment]
There is a separate repo for .NET Core examples [here](https://github.com/telerik/aspnet-core-examples).

However, this example is not ported there. We will do our best to include similar example in the .NET Core repo as soon as possible.
