### ISSUE TITLE
Export with Groupable option

### ISSUE THREAD

**Issue by pyasui** [telerik/ui-for-aspnet-mvc-examples#22]
Hi

I do not know if it's the right place to post a doubt but I'd like to ask a question.

How can I do the same thing as the sample (https://github.com/telerik/ui-for-aspnet-mvc-examples/tree/master/grid/excel-export-server-side) including the Grouping data feature whic returns a Kendo.Mvc.Infrastructure.AggregateFunctionsGroup instead of list?

Thank you!

**Comment by VicTachev** [comment]
Please submit a ticket for any technical questions you have. We will be happy to assist.
