### ISSUE TITLE
EditorTemplateName is not bounded properly in grid hierarchy

### ISSUE THREAD

**Issue by gabon** [telerik/ui-for-aspnet-mvc-examples#23]
Hi,
It looks like the dropdown in the nested grid are bounded by HTML id, so if you try to click edit on two different sublevels only one will be bonded properly.

Screenshot from ajax-3-level-hierarchy-editing example:
![image](https://user-images.githubusercontent.com/1451051/47802946-ab303780-dd31-11e8-894e-e07e1f5d3289.png)

The bug is also in 2018.2.620. Is there a workaround?

**Comment by VicTachev** [comment]
Please submit a ticket for any technical questions you have. We will be happy to assist.
