### ISSUE TITLE
Link to main example kendo code in Readme

### ISSUE THREAD

**Issue by hawkerm** [telerik/ui-for-aspnet-mvc-examples#3]
Since there's a lot setting up this full example project.  It'd be nice to have a link to the index.cshtml file that actually represents the main kendo-ui portion of the example.  It took me a while to find initially before thinking of searching on 'odata-v4' (though I knew that was something I was looking for ahead of time from other threads which led me here).

**Comment by KirilNN** [comment]
It is a good idea to link them to the existing list of resources http://docs.telerik.com/kendo-ui/introduction#github-public-example-repositories

**Comment by KirilNN** [comment]
added with https://github.com/telerik/kendo-ui-core/commit/c1c100d18dec85421289b98f95d863dc6a3f596c
