### ISSUE TITLE
Scheduler server filtering example with error in chrome console

### ISSUE THREAD

**Issue by bdongus** [telerik/ui-for-aspnet-mvc-examples#8]
Starting your demo I accidentally had developer tools opened and noticed that jquery and the file "/" are included more than once.

Here is what the console log shows:

> Detected Kendo UI version: "2015.3.930"
> VM466:170 jQuery is included more than once
> VM466:170 Kendo file / is included more than once(anonymous function) @ VM466:170(anonymous function) @ VM466:169req.onreadystatechange @ VM466:148XMLHttpRequest.send (async)check_can_load @ VM466:155(anonymous function) @ VM466:160diagnose_scripts @ VM466:159(anonymous function) @ VM466:190

**Comment by AloeDream** [comment]
Any updates? I also have this issue, using kendo extention for Chrome.

> VM96757:170 Kendo file / is included more than once

**Comment by mparvanov** [comment]
Thank you for bringing this issue to our attention. The demo has been resolved and the fix is to remove the redundant duplicated references from _Layout.cshtml:

@Scripts.Render("~/bundles/modernizr")
<script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
